name: Build Test

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: gfortran on macos
        run: |
          # make sure gfortran is available
          ls /usr/local/bin/gfortran*
          ls /usr/local/Cellar/gcc*
          gfortran-11 --version
