name: Build Test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: gfortran
        run: |
          # make sure gfortran is available
          if [ ${{ matrix.os }} == macos-latest ]
          then
            ls /usr/local/bin/gfortran*
            ls /usr/local/Cellar/gcc*
          fi
          if [ ${{ matrix.os }} == ubuntu-latest ]
          then
            which gfortran
            which gfortran-12
          fi
      - name: build, test
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ctest
          
