name: Build Test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: gfortran
        run: |
          # make sure gfortran is available
          ls /usr/local/bin/gfortran*
          ls /usr/local/Cellar/gcc*
